#!/bin/bash

#SBATCH --account=rubin:developers      # Account name
#SBATCH --partition=milano
#
#SBATCH --job-name=tcu_2552
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --nodes=1                       # Number of nodes
#SBATCH --ntasks=4
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=20g
#
#SBATCH --time=2-14:10:00
#SBATCH --chdir=/sdf/data/rubin/shared/fbs_sims/sims_featureScheduler_runs5.2/templates_cleanup
#SBATCH --mail-user=yoachim@uw.edu
#
##turn on e-mail notification
#SBATCH --mail-type=ALL
#SBATCH --mail-user=yoachim@uw.edu

## Set up the evironment
source ~/anaconda3/etc/profile.d/conda.sh
conda activate rubin12
export OPENBLAS_NUM_THREADS=1

#python templates_cleanup_25.py


rm maf2.sh
 
ls templates_cleanup_25*_10yrs.db | xargs -I'{}' echo "scimaf_dir --db '{}'" > maf2.sh
ls templates_cleanup_25*_10yrs.db | xargs -I'{}' echo "glance_dir --db '{}'" >> maf2.sh
ls templates_cleanup_25*_10yrs.db | xargs -I'{}' echo "ddf_dir --db '{}'" >> maf2.sh
ls templates_cleanup_25*_10yrs.db | xargs -I'{}' echo "metadata_dir --db '{}'" >> maf2.sh

#generate_ss
#grep templates_cleanup_25 ss_script.sh >> maf2.sh
 
cat maf2.sh | parallel -j 4
